$(function(){
    $(document).ready(function(){
        console.log("kontiwa");
        $('.slider').slick({
            autoplay:true,
            autoplaySpeed:5000,
            dots:true,
        });
    });
})
